version: '3.8'

services:
  # CONTENEDOR 1: LA BASE DE DATOS MYSQL
  db-servicio:
    image: mysql:8.0
    container_name: mysql_autenticacion
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: db_amazorg_auth 
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports:
      - "3306:3306"
    networks:
      - red_interna_proyecto
    volumes:
      - persistencia_db:/var/lib/mysql

  # CONTENEDOR 2: EL ENTORNO DE TRABAJO JAVA/SPRING BOOT
  workspace-java:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_programacion_autenticacion
    ports:
      - "8081:8081"
    depends_on:
      - db-servicio
    networks:
      - red_interna_proyecto
    command: tail -f /dev/null
    volumes:
      - .:/app # CORREGIDO: Mapea la raíz actual donde están pom.xml y src
    working_dir: /app

networks:
  red_interna_proyecto:

volumes:
  persistencia_db:

